### ISSUE TITLE
Can‘t pull image, permission denied

### ISSUE THREAD

**Issue by jinmiaoluo** [bentoml/OCR-as-a-Service#4]
Unable to pull image from ghcr.io, I initially thought it was due to missing login information, but even after logging in with a Personal Access Token, it still shows "Cannot pull image, permission denied"，I don't know if this is an exception or if other people will encounter the same problem.
![image](https://github.com/bentoml/OCR-as-a-Service/assets/39730824/23b50e6a-0992-4ea0-83e7-0c3a2fffeee6)

**Comment by aarnphm** [comment]
oh sorry, we forgot to make the image public. Can you try again?

**Comment by jinmiaoluo** [comment]
I have tested it and now I can pull the image normally.
